#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frome FM

# this means to ignore newlines until "baseurl:"
description: A radical fresh approach to radio. A trully shared resource. Open and transparent. Supporting the local community and empowering the collective creativity of its members 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frome.fm" # the base hostname & protocol for your site
#These settings might be able to go?
author: Felipe Ieder
twitter_username: fromefm
github_username:  druidalabs/frome.fm


# Build settings
markdown: kramdown

permalink: /event/:title.html

